# name: CI Pipeline

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   test-node:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: backend
#     steps:
#       - uses: actions/checkout@v3
#       - name: Instalar Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18
#       - name: Instalar dependencias
#         run: npm install
#       - name: Ejecutar pruebas
#         run: npm test

#   run-python:
#     runs-on: ubuntu-latest
#     defaults:
#       run:
#         working-directory: scripts
#     steps:
#       - uses: actions/checkout@v3
#       - name: Ejecutar script Python
#         run: python main.py



name: CI - Test calculadora

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test
