name: CI + Deploy a GitHub Pages + Discord

on:
  push:
    branches: [main]  
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install
      
      - name: Build project
        run: npm run build  

      - name: Ejecutar tests
        run: npm test

      - name: Publicar en GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages         
          folder: build           

  notify-discord-success:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [test-and-build]
    steps:
      - name: Notificar éxito a Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content":"✅ *CI + Deploy EXITOSO* en `${{ github.repository }}` para `${{ github.sha }}` por `${{ github.actor }}`."}' \
            $DISCORD_WEBHOOK

  notify-discord-failure:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [test-and-build]
    steps:
      - name: Notificar error a Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content":"❌ *CI + Deploy FALLÓ* en `${{ github.repository }}` para `${{ github.sha }}` por `${{ github.actor }}`.\n🔍 Ver errores: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }' \
            $DISCORD_WEBHOOK
