name: CI con Notificación Discord

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests
        run: npm test

  notify-discord-success:
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [test-node]
    steps:
      - name: Notificar éxito a Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content":"✅ *CI EXITOSO* en `${{ github.repository }}` para el commit `${{ github.sha }}` por `${{ github.actor }}`."}' \
            $DISCORD_WEBHOOK

  notify-discord-failure:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [test-node]
    steps:
      - name: Notificar error a Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d '{"content":"❌ *CI FALLÓ* en `${{ github.repository }}` para el commit `${{ github.sha }}` por `${{ github.actor }}`. Revisa los logs en: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }' \
            $DISCORD_WEBHOOK
