name: CI con Notificación Discord

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-node:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar pruebas
        run: npm test

  run-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts
    steps:
      - uses: actions/checkout@v3
      - name: Ejecutar script Python
        run: python main.py

  notify-discord:
    runs-on: ubuntu-latest
    needs: [test-node, run-python]
    steps:
      - name: Notificación a Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json"             -X POST             -d '{"content":"✅ CI completado correctamente en *${{ github.repository }}* para el commit `${{ github.sha }}`."}'             $DISCORD_WEBHOOK
